#encoding: utf-8
'''
@author:alvin.zhu
@file:test_Video_detail.py
@time:2020/11/6 14:45
@Description:

'''
import time
from Public.Unittest_import import Dubbing

class Video_detail(Dubbing):
    def test_a(self):
        self.V.Into_vi deo()
        self.V.Head_into_zoom_back()
        self.V.Video_follow()
        self.V.Video_good()
        self.V.Video_exposure_touch()
        self.V.Video_exposure_gold()
        self.V.Video_exposure_freevip()
        self.V.Video_exposure_diamond()
        self.V.Video_comments()
        self.V.Video_comment_send()
        self.V.Video_comment_report()
        self.V.Video_comments_load()
        self.V.Video_Coor_dubbing()
        self.V.Video_source()
        self.V.Video_share()
        self.V.Video_switch()

class Person_center(Dubbing):
    def test_a(self):
        self.P.Person_My()
        self.P.Person_into_my_zoom()
        self.V.Btnback()
        self.P.Person_home_into_follow()
        self.P.Person_home_into_fans()
        self.P.Person_copy_ID()
        self.P.Person_into_my_zoom()
        self.P.Person_Zoom_works_search()
        self.P.Person_Zoom_source_search()
        self.P.Person_Zoom_edit_info()
        self.P.Person_Zoom_change_gender()
        self.P.Person_Zoom_change_head()
        self.P.Person_Zoom_Introduction()
        self.P.Person_Zoom_change_area()
        self.P.Person_Zoom_change_birthday()
        self.P.Person_Zoom_username_check()
        self.P.Person_Zoom_Vip_headwear()
        self.P.Person_Zoom_Vip_Dress()
        self.P.Person_Zoom_user_level()
        self.P.Person_Zoom_Authentication()
        self.P.Person_Zoom_fans()
        self.V.Btnback()
        self.P.Person_Zoom_follows()
        self.V.Btnback()
        self.P.Person_Zoom_Societies()
        self.V.Btnback()
        self.P.Person_Zoom_Crunchies_list()
        self.P.Person_Zoom_work_list()
        self.P.Person_Zoom_work_switch_label()
        self.P.Person_Zoom_work_top()
        self.P.Person_Zoom_work_delete()
        self.P.Person_Zoom_coors()
        self.P.Person_Zoom_coor_invite()
        self.P.Person_Zoom_coor_Private_public()
        self.P.Person_Zoom_coor_delete()
        self.P.Person_Zoom_source_preview()
        self.P.Person_Zoom_Source_dubbing()
        self.P.Person_Zoom_goods_record()
        self.V.Btnback()
        self.P.Person_Zoom_forward()
        self.P.Person_Zoom_post_list()
        self.P.Person_Zoom_forword_and_delete()
        self.P.Person_chat_list()
        self.P.Person_Zoom_create_compilation()
        self.P.Person_Zoom_delete_compilation()
        self.P.Person_Zoom_quit()
        self.P.Person_Vip_enter()
        self.P.Person_Vip_Equity()
        self.P.Person_Vip_Price()
        self.P.Person_Vip_Give()
        self.P.Person_Vip_Privileges()
        self.P.Person_Cp_invite()
        self.P.Person_Cp_Zoom()
        self.P.Person_Daren()
        self.P.Person_System_Notices()
        self.P.Person_Good_Notices()
        self.P.Person_Coor_Notices()
        self.P.Person_Coor_Dubbing()
        self.P.Person_Coor_delete()
        self.P.Person_Coor_Generate_works()
        self.P.Person_Coor_video_play()
        self.P.Person_Coor_Notice_setting()
        self.P.Person_Comment_Notices()
        self.P.Person_Comment_follows()
        self.P.Person_Comment_video_detail()
        self.P.Person_Comment_Reply()
        self.P.Person_Comment_Post_Notices()
        self.P.Person_Chat_Notices()
        self.P.Person_chat_user_list()
        self.P.Person_User_Chat()
        self.P.Person_Chat_Report()
        self.P.Person_Chat_User_Zoom()
        self.P.Person_Chat_list_delete()
        self.P.Person_Chat_Not_follow()
        self.P.Person_Vip_Draft_synchronous()
        self.P.Person_Draft_reload()
        self.P.Person_Draft_Video_Preview()
        self.P.Person_Draft_Repeat()
        self.P.Person_Draft_Reassignment()
        self.P.Person_Already_source_list()
        self.P.Person_Already_source_dubbing()
        self.P.Person_Alread_Source_delete()
        self.P.Person_Alread_Source_delete_network()
        self.P.Person_Alread_Source_Bulk_deletion()
        self.P.Person_Source_collection()
        self.P.Person_Source_collection_refresh()
        self.P.Person_Already_source_dubbing()
        self.P.Person_Alread_Source_delete()
        self.V.Btnback()
        self.P.Person_Self_control_source()
        self.P.Person_Self_Control_Video_Select()
        self.P.Person_Self_Control_Video_Clip()
        self.P.Person_Self_Control_Source_delete()
        self.V.Btnback()
        self.P.Person_My_Wealth()
        self.P.Person_My_earnings()
        self.P.Person_My_achievements()
        self.P.Person_Invite_friend()
        self.P.Person_Points_Mall()
        self.P.Person_Mode_switch()

