# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Test(object):
    def setupUi(self, Test):
        Test.setObjectName("Test")
        Test.resize(999, 675)
        self.pushButton = QtWidgets.QPushButton(Test)
        self.pushButton.setGeometry(QtCore.QRect(60, 60, 251, 71))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(Test)
        self.textEdit.setGeometry(QtCore.QRect(60, 180, 841, 371))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Test)
        self.pushButton.clicked.connect(self.textEdit.show)
        QtCore.QMetaObject.connectSlotsByName(Test)

    def retranslateUi(self, Test):
        _translate = QtCore.QCoreApplication.translate
        Test.setWindowTitle(_translate("Test", "Form"))
        self.pushButton.setText(_translate("Test", "PushButton"))
