# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.setWindowModality(QtCore.Qt.NonModal)
        widget.setEnabled(False)
        widget.resize(830, 722)
        self.Memory = QtWidgets.QPushButton(widget)
        self.Memory.setEnabled(False)
        self.Memory.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.Memory.setObjectName("Memory")
        self.Mem_list = QtWidgets.QTextEdit(widget)
        self.Mem_list.setGeometry(QtCore.QRect(100, 10, 111, 471))
        self.Mem_list.setObjectName("Mem_list")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "性能测试工具"))
        self.Memory.setText(_translate("widget", "内存"))
